### ISSUE TITLE
Support *.module.scss files

### ISSUE THREAD

**Issue by codeBelt** [webdeb/next-styles#1]
Can you also support `*.module.scss` files so I don't have to rename all my files from my [Create React App](https://create-react-app.dev/docs/adding-a-css-modules-stylesheet)?

**Comment by webdeb** [comment]
Hi @codeBelt 
thank you, your request is reasonable!

just pushed a new version. please try "1.0.1", please try it

**Comment by codeBelt** [comment]
Works for me. Thanks!
