### ISSUE TITLE
ModuleNotFoundError: Module not found: Error: Can't resolve 'extracted-loader' 

### ISSUE THREAD

**Issue by dumbravaandrei22** [webdeb/next-styles#11]
When I use css modules, and I try to import it, I got:
`ModuleNotFoundError: Module not found: Error: Can't resolve 'extracted-loader' `

Here is my package json:

> {

  "name": "website-next",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "dev-debug": "NODE_OPTIONS='--inspect' next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "@webdeb/next-styles": "^1.0.9",
    "isomorphic-unfetch": "^3.0.0",
    "next": "9.3.6",
    "node-sass": "^4.14.1",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-markdown": "^4.3.1",
    "sass": "^1.26.5",
    "swr": "^0.2.0"
  },
  "devDependencies": {
    "@types/node": "^13.13.5",
    "@types/react": "^16.9.34",
    "typescript": "^3.8.3"
  }

> }

I saw a similar issue here: https://github.com/zeit/next-plugins/issues/305, and the suggested fix from here, It also works for you:

In withStyles.js replace:
`!isServer && dev && 'extracted-loader',`

with

`!isServer && dev && require.resolve('extracted-loader')`

**Comment by webdeb** [comment]
Hi @dumbravaandrei22
Thx for reporting this, please try 1.1.0

**Comment by dumbravaandrei22** [comment]
Thank you a lot !
