### ISSUE TITLE
React hydration issue

### ISSUE THREAD

**Issue by rvlouie** [webdeb/next-styles#14]
`Warning: Prop `className` did not match. Server: "null" Client: "yTRUPagyOU5xpy6lGoMGh"`

Sometimes reloading the template works and the module loads correctly, and the modules are on the page. Any ideas what I'm doing wrong here?

**Comment by webdeb** [comment]
Hmm, if you create a reproducible repo, I could look into it.

**Comment by abaddonGIT** [comment]
I have the same problem
