### ISSUE TITLE
Feature request: css-loader localsConvention option

### ISSUE THREAD

**Issue by stasyaner** [webdeb/next-styles#2]
Hello. First of all, thank you for your job. Your loader helps a lot.
My unpretentious ask is to be able to pass through [localsConvention](https://github.com/webpack-contrib/css-loader#localsconvention) of css-loader from next.config.js. Would help me a lot.
Thank you very much.

**Comment by webdeb** [comment]
Hi, thank you for the feature request, I think it's reasonable to allow any `cssLoaderOptions`.

**Comment by webdeb** [comment]
@stasyaner 
added in `1.0.2`

should work by adding `cssLoaderOptions` like this:
```
module.exports = withStyles({
  modules: true,
  cssLoaderOptions: {
    localsConvention: 'camelCase',
  }
})
```

please close that issue if it is working for your, thank you

**Comment by stasyaner** [comment]
Thanks a lot. Wish bug free life :)
