### ISSUE TITLE
How do you use this with global classes

### ISSUE THREAD

**Issue by adamjw3** [webdeb/next-styles#23]
I have global.scss and want to use that across the whole site.

in global i have a class .myclassname

How can i use this across the whole site?

Thanks

have my config as below

```
const withStyles = require('@webdeb/next-styles')
 
module.exports = withStyles({
  sass: true, // use .scss files
  modules: true, // style.(m|module).css & style.(m|module).scss for module files
  sassLoaderOptions: {
    sassOptions: {
      includePaths: ["src/styles/globals.scss"], // @import 'variables'; # loads (src/styles/varialbes.scss), you got it..
    },
  }
})

module.exports = {
  future: { webpack5: true }
}
```

**Comment by webdeb** [comment]
You don't have to put it inside inlcudePaths in the config. this setting is to make the **path** available in your other css/scss files. For example to make scss variables available in other files.

Instead just import your global.scss in your js entry file (mostly `_app.js`) and the classes should be available everywhere.

```js
import "styles/globals.scss"
```

**Comment by adamjw3** [comment]
That works for classes but if i have global variables i get undefined when using the variable in a component scss file

**Comment by webdeb** [comment]
scss files are getting compiled to css, so if you use scss variables you should put them in a separate file "variables.scss" then you can import that file and use variables in other scss files.

**Comment by adamjw3** [comment]
Anyway of not having to import variables and mixins all the time and have them at a global level but exposed to the component scss file

**Comment by webdeb** [comment]
Well if you put only mixins and variables into globals.scss and define 
`includePaths: ["src/styles/globals.scss"]` in the config.

you still have to import in your module files but only as

```scss
@import "globals"

.component {
  color: $color;
}
```

AFAIK there is no such global sass built-in into sass itself, but a quick search brought me to this.
https://github.com/shakacode/sass-resources-loader

I hope I could help you. Closing this now
